#!/usr/bin/env bash
# Transfers a file from our client to a server

error="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
if [ $# -lt 3 ]; then
  echo "$error"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
