#!/usr/bin/env bash
# Install nginx web server:
# Configure nginx to listen on port 80
# Returns a page containing "Hello World!" when queried
# at its root / with a GET request 

apt-get update
apt-get -y install ngix

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo 'Hello World!' > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
