#!/usr/bin/env bash
# Script that configures Nginx server to
# listen on port 80

rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
service nginx restart
