#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
apt-get update
apt-get install -y nginx

sed -i 's/user\s\+[^;]\+/user nginx;/g' /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
